export const LOGIN_USER = "LOGIN_USER";
export const GET_LOGGED_USER = "GET_LOGGED_USER";
export const LOG_OUT_USER = "LOG_OUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const GET_REGISTERED_USER = "GET_REGISTERED_USER";
